### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/rd.gz'

### ISSUE THREAD

**Issue by chinen222** [bkerler/android_universal#2]
Vanilla running the script, and it doesn't create the archive. Using Linux Mint 20.

**Comment by bkerler** [comment]
That happens if the boot image doesn't have a ramdisk, for example on android 10-11 images.

**Comment by chinen222** [comment]
Aaah ! Ramdisk is in recovery for non A/B devices , Thanks
